var relearn_search_index=[{content:`updated 01/26/2023
This page lists some of the software you might need when following along with the book. This page will be kept up to date with the latest and greatest.
IDEs An Integrated Development Environment, or “IDE” is a piece of software that provides a comprehensive and featureful environment for writing code, including things like autocompletion, folder management, debugging and so on.
Visual Studio Code Links
Visual Studio Code Homepage Download VSCode Download the Go Extension Visual Studio Code (VSCode)is a powerful free IDE based on Electron, which makes it cross-platform. To set it up, first install VSCode from thw download link above, and then install the Go extension. Then, once you’ve opened the app, go to File -\u003e Add Folder To Workspace and navigate to your home folder, documents folder, or wherever you want to put the directory, or workspace, for working on code from the book. Click New Folder and create a folder called goinaction.
Then open the command palette by hitting CMD-shift-p or Windows-shift-P and type go mod so it will highlight the Go: Initialize go mod option. hit enter and type goinaction when prompted. Save the generated go.mod , and you should be ready to Go!
Terminal Emulators Terminal emulators, are so-called because they “emulate” the experience of using a terminal interface, whether or not your sustem has one built in. But, really, they are often much more than that, and some of them provide a lot of sophisticated functionality to make the experience flexible, powerful and convenient.
The following is a (far from exhaustive) list of some popular terminal emulators you might want to consider when doing work on the command line.
Terminal Emulators for Windows Windows Terminal The official MS Terminal app is actually pretty good! Definitely the best place to start if you’re unfamiliar. Cmder - A well-designed app by a terminal enthusiast. Fully featured and portable with Linux commands integrated into the bundled “Git For Windows”, which also comes with Git, so there’s that! MobaXterm - If you’re looking for batteries-included, this is it, but it might be a little much for most users. You can also enable WSL if you’re feeling a bit more adventurous. This will enable to to run a Linux environment alongside Windows.
Terminal Emulators for macOS iTerm2 - The classic is still the best. You can’t go wrong with iTerm2. It’s what I use every day. Alacrittu - Very fast, if that matters to you, thanks to its OpenGL rendering engine. Configuration is done with text files though, and you’ll have to locate them on disk, so it’s not nearly as easy to get set up as iTerm2. Works on Linux, too. Warp - The new kid on the block, but this is definitely some next-level stuff with advanced views, graphical integration, multi cursors, and the lot. Just make sure you read the privacy statements and opt-out of telemetry if you’re concerned about it. Terminal Emulators for Linux Let’s be honest, you probably know what you’re doing when it comes to terminal emulators, but here are some options anyways.
Kitty - Like Alacritty, it’s a hardware-accelerated terminal. Also like Alacritty, you will need to configure it with text, but at least the config file is well-documented and easy to access. Alacritty also works on Linux Foot - Fast and featureful with commandline graphics, thanks to libsixel. Also application integration for things like loading links in the browser for you, if you want. `,description:"",tags:null,title:"Software",uri:"/software/index.html"},{content:"",description:"",tags:null,title:"Categories",uri:"/categories/index.html"},{content:"",description:"",tags:null,title:"Tags",uri:"/tags/index.html"}]